#!/bin/bash

action=$1
pending_dir=$4
postfix_main_cf="${pending_dir}/../postfix/etc/postfix/main.cf"

[[ "$action" == "pre" ]] || exit 0
[[ -e "$postfix_main_cf" ]] || exit 0

sed -e "s@^alias_maps\s*=\s*\(.*\)@alias_maps = \1,hash:/var/lib/mailman/data/aliases@" \
    -e "s@^virtual_alias_maps\s*=\s*\(.*\)@virtual_alias_maps = hash:/var/lib/mailman/data/virtual-mailman,\1@" \
    -i $postfix_main_cf
