#!/bin/bash
app=mailman

domain=$(sudo yunohost app setting $app domain)

# Remove mailman and fcgiwrap
sudo apt-get remove mailman fcgiwrap <<< "Y"

# Backup current postfix configuration 
sudo cp /etc/postfix/main.cf /etc/postfix/main.cf.beforeMailmanRemove
# Restore postfix configuration prior to mailman install
sudo mv /etc/postfix/main.cf.beforeMailmanInstall /etc/postfix/main.cf

# Remove nginx conf for this app
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf

