#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get "$app" domain)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE DEPENDENCIES
#=================================================

ynh_remove_app_dependencies
apt-get remove mailman --purge

#=================================================
# REMOVE REMAINING FILES
#=================================================

# We need to remove this otherwise mailman will do some shit when reinstalling
ynh_secure_remove "/var/lib/mailman"

# Remove hook for postfix conf
ynh_secure_remove "/usr/share/yunohost/hooks/conf_regen/98-postfix_mailman"

#=================================================
# REMOVE THE NGINX CONFIGURATION
#=================================================

ynh_remove_nginx_config

#=================================================
# RELOAD SERVICES / CONF
#=================================================

yunohost service regen-conf postfix
ynh_systemd_action --service_name=postfix --action=restart
ynh_systemd_action --service_name=nginx --action=reload
